var _yt_www={};(function(m){var window=this;var qa,ra;m.aa=function(a){return function(){return m.ba[a].apply(this,arguments)}};m.da=function(a){return void 0!==a};m.l=function(a,b,c){a=a.split(".");c=c||m.ea;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&m.da(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};m.n=function(a,b){for(var c=a.split("."),d=b||m.ea,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};m.fa=function(){};m.ga=function(a){a.getInstance=function(){return a.Qb?a.Qb:a.Qb=new a}};
m.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};m.ia=function(a){return"array"==m.ha(a)};m.ja=function(a){var b=m.ha(a);return"array"==b||"object"==b&&"number"==typeof a.length};m.ka=function(a){return"string"==typeof a};m.la=function(a){return"number"==typeof a};m.na=function(a){return"function"==m.ha(a)};m.oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};m.pa=function(a){return a[qa]||(a[qa]=++ra)};
var sa=function(a,b,c){return a.call.apply(a.bind,arguments)};var ta=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};m.q=function(a,b,c){m.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?sa:ta;return m.q.apply(null,arguments)};
m.r=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};m.t=function(a,b){function c(){}c.prototype=b.prototype;a.D=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[c].apply(a,h)}};var ua=function(a){ua[" "](a);return a};m.va=function(a,b){try{return ua(a[b]),!0}catch(c){}return!1};
m.wa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,m.wa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};m.xa=function(a){return(0,window.encodeURIComponent)(String(a))};
m.ya=function(a){if(!za.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Aa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ba,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ca,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Da,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ea,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Fa,"&#0;"));return a};m.Ga=function(a,b){return-1!=a.indexOf(b)};m.Ha=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
m.Ia=function(a,b){for(var c=0,d=(0,m.Ka)(String(a)).split("."),e=(0,m.Ka)(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var k=d[h]||"",p=e[h]||"",v=RegExp("(\\d*)(\\D*)","g"),x=RegExp("(\\d*)(\\D*)","g");do{var O=v.exec(k)||["","",""],ca=x.exec(p)||["","",""];if(0==O[0].length&&0==ca[0].length)break;c=La(0==O[1].length?0:(0,window.parseInt)(O[1],10),0==ca[1].length?0:(0,window.parseInt)(ca[1],10))||La(0==O[2].length,0==ca[2].length)||La(O[2],ca[2])}while(0==c)}return c};
var La=function(a,b){return a<b?-1:a>b?1:0};var Ma=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;return b};m.Na=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};m.Oa=function(a){var b=m.ka(void 0)?m.Ha(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};m.Pa=function(a,b,c){b=m.Qa(a,b,c);return 0>b?null:m.ka(a)?a.charAt(b):a[b]};
m.Qa=function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};m.Ra=function(a,b){return 0<=(0,m.Sa)(a,b)};m.Ta=function(a,b){var c=(0,m.Sa)(a,b),d;(d=0<=c)&&m.Ua(a,c);return d};m.Ua=function(a,b){m.Va.splice.call(a,b,1)};m.Wa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};m.u=function(){this.qb=this.qb;this.ab=this.ab};m.Xa=function(a,b){m.Ya(a,m.r(m.Za,b))};
m.Ya=function(a,b){a.qb?b.call(void 0):(a.ab||(a.ab=[]),a.ab.push(m.da(void 0)?(0,m.q)(b,void 0):b))};m.Za=function(a){a&&"function"==typeof a.dispose&&a.dispose()};m.$a=function(){m.u.call(this);this.Ya=[];this.Bc={}};m.ab=function(a){bb(m.cb,arguments)};m.w=function(a,b){return a in m.cb?m.cb[a]:b};m.y=function(a,b){m.na(a)&&(a=m.db(a));return window.setTimeout(a,b)};m.eb=function(a,b){m.na(a)&&(a=m.db(a));return window.setInterval(a,b)};m.fb=function(a){window.clearTimeout(a)};m.gb=function(a){window.clearInterval(a)};
m.db=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw m.hb(b),b;}}:a};m.hb=function(a,b){var c=m.n("yt.www.errors.log");c?c(a,b):(c=m.w("ERRORS")||[],c.push([a,b]),m.ab("ERRORS",c))};m.ib=function(a){return a in m.jb};m.kb=function(a,b,c){var d=b||{};if(a=a in m.jb?m.jb[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});return a};var bb=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
m.z=function(a,b,c){var d=lb();if(d){var e=d.subscribe(a,function(){if(!m.mb||m.mb!=e){var d=arguments,h=function(){nb[e]&&b.apply(c||window,d)};try{ob[a]?h():m.y(h,0)}catch(k){m.hb(k)}}},c);nb[e]=!0;pb[a]||(pb[a]=[]);pb[a].push(e);return e}return 0};m.qb=function(a){var b=lb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,m.A)(a,function(a){b.unsubscribeByKey(a);delete nb[a]}))};m.B=function(a,b){var c=lb();return c?c.publish.apply(c,arguments):!1};
m.rb=function(a,b){ob[a]=!0;var c=lb(),c=c?c.publish.apply(c,arguments):!1;ob[a]=!1;return c};var lb=function(){return m.n("yt.pubsub.instance_")};m.sb=function(){return!!m.n("yt.scheduler.instance")};m.tb=function(a,b){void 0===b&&(b=window.NaN);var c=m.n("yt.scheduler.instance.addJob");return c?((0,window.isNaN)(b)&&(b=0),c(a,0,b)):(0,window.isNaN)(b)?(a(),window.NaN):m.y(a,b||0)};m.ub=function(a,b){return m.tb(a,b)};m.vb=function(a){var b=m.n("yt.scheduler.instance.cancelJob");b?b(a):m.fb(a)};
m.wb=function(a){for(var b=0,c=a.length;b<c;b++)m.vb(a[b])};m.xb=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.A=d?m.db(d):null;this.n=e?m.db(e):null;this.Ya=[];this.j=this.k=0};m.yb=function(a){m.vb(a.k);a.k=m.ub((0,m.q)(a.init,a))};m.zb=function(a){a.name in Ab&&Bb(a.name);Ab[a.name]={reqs:[],disable:(0,m.q)(a.disable,a)};(0,m.A)(a.deps,function(b){if(!(b in Ab))throw Error("Module "+b+" required by "+a.name);Ab[b].reqs.push(a.name)});a.enable()};
var Bb=function(a){if(a in Ab){var b=Ab[a];(0,m.A)(b.reqs,function(a){Bb(a)});try{b.disable()}catch(c){}delete Ab[a]}};m.Cb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};m.Db=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};m.Eb=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};m.Gb=function(a,b){b in a&&delete a[b]};m.Hb=function(a,b,c){if(b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};m.Ib=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
m.Jb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Kb.length;f++)c=Kb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};m.Lb=function(a){var b=arguments.length;if(1==b&&m.ia(arguments[0]))return m.Lb.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};m.Mb=function(){this.j="";this.k=Nb};m.Ob=function(a){return a instanceof m.Mb&&a.constructor===m.Mb&&a.k===Nb?a.j:"type_error:Const"};
m.Pb=function(){this.j="";this.k=Qb};m.Rb=function(a){return a instanceof m.Pb&&a.constructor===m.Pb&&a.k===Qb?a.j:"type_error:SafeStyle"};var Sb=function(a){var b=new m.Pb;b.j=a;return b};m.Tb=function(){this.j="";this.k=Ub};m.Vb=function(a){return a instanceof m.Tb&&a.constructor===m.Tb&&a.k===Ub?a.j:"type_error:SafeUrl"};m.Wb=function(a){if(a instanceof m.Tb)return a;a=a.Ye?a.Oe():String(a);a=Xb.test(a)?Yb(a):"about:invalid#zClosurez";var b=new m.Tb;b.j=a;return b};
var Yb=function(a){try{var b=(0,window.encodeURI)(a)}catch(c){return"about:invalid#zClosurez"}return b.replace(Zb,function(a){return $b[a]})};var ac=function(){this.j=bc};m.cc=function(){this.j="";this.l=dc;this.k=null};m.ec=function(a){return a instanceof m.cc&&a.constructor===m.cc&&a.l===dc?a.j:"type_error:SafeHtml"};
var fc=function(a){function b(a){if(m.ia(a))(0,m.A)(a,b);else{var f;a instanceof m.cc?f=a:(f=null,a.vk&&(f=a.Lg()),a=m.ya(a.Ye?a.Oe():String(a)),f=m.gc(a,f));d+=m.ec(f);f=f.Lg();0==c?c=f:0!=f&&c!=f&&(c=null)}}var c=0,d="";(0,m.A)(arguments,b);return m.gc(d,c)};m.gc=function(a,b){var c=new m.cc;c.j=a;c.k=b;return c};
m.hc=function(a,b){var c=null,d="<"+a;if(b)for(var e in b){if(!ic.test(e))throw Error('Invalid attribute name "'+e+'".');var f=b[e];if(null!=f){var h,k=a;h=e;if(f instanceof m.Mb)f=m.Ob(f);else if("style"==h.toLowerCase()){if(!m.oa(f))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof f+" given: "+f);if(!(f instanceof m.Pb)){var k="",p=void 0;for(p in f){if(!/^[-_a-zA-Z0-9]+$/.test(p))throw Error("Name allows only [-_a-zA-Z0-9], got: "+p);var v=f[p];
if(null!=v){if(v instanceof m.Mb)v=m.Ob(v);else if(jc.test(v)){for(var x=!0,O=!0,ca=0;ca<v.length;ca++){var ma=v.charAt(ca);"'"==ma&&O?x=!x:'"'==ma&&x&&(O=!O)}x&&O||(v="zClosurez")}else v="zClosurez";k+=p+":"+v+";"}}f=k?Sb(k):kc}f=m.Rb(f)}else{if(/^on/i.test(h))throw Error('Attribute "'+h+'" requires goog.string.Const value, "'+f+'" given.');if(h.toLowerCase()in lc)if(f instanceof ac)f=f instanceof ac&&f.constructor===ac&&f.j===bc?"":"type_error:TrustedResourceUrl";else if(f instanceof m.Tb)f=m.Vb(f);
else throw Error('Attribute "'+h+'" on tag "'+k+'" requires goog.html.SafeUrl or goog.string.Const value, "'+f+'" given.');}f.Ye&&(f=f.Oe());h=h+'="'+m.ya(String(f))+'"';d=d+(" "+h)}}e=void 0;m.da(e)?m.ia(e)||(e=[e]):e=[];!0===mc[a.toLowerCase()]?d+=">":(c=fc(e),d+=">"+m.ec(c)+"</"+a+">",c=c.Lg());(e=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(e)?c=0:c=null);return m.gc(d,c)};m.nc=function(a,b){a.innerHTML=m.ec(b)};m.C=function(a,b){return a?a.dataset?a.dataset[m.oc(b)]:a.getAttribute("data-"+b):null};
m.pc=function(a,b){return a?a.dataset?m.oc(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};m.oc=function(a){return qc[a]||(qc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};m.rc=function(a,b){var c=m.sc(a);window.spf.script.load(a,c,b)};
m.sc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(tc,""),b=b.replace(uc,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};m.vc=function(a,b,c){return Math.min(Math.max(a,b),c)};m.wc=function(a,b){this.x=m.da(a)?a:0;this.y=m.da(b)?b:0};m.xc=function(a){return m.Ga(m.yc,a)};var zc=function(){return m.xc("Opera")||m.xc("OPR")};var Ac=function(){return m.xc("Edge")||m.xc("Trident")||m.xc("MSIE")};
var Bc=function(){return(m.xc("Chrome")||m.xc("CriOS"))&&!zc()&&!Ac()};var Cc=function(){return m.xc("Edge")};m.Dc=function(){return m.xc("iPhone")&&!m.xc("iPod")&&!m.xc("iPad")};var Ec=function(){var a=m.yc;if(m.Fc)return/rv\:([^\);]+)(\)|;)/.exec(a);if(m.D&&Cc())return/Edge\/([\d\.]+)/.exec(a);if(m.D)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(m.Gc)return/WebKit\/(\S+)/.exec(a)};var Hc=function(){var a=m.ea.document;return a?a.documentMode:void 0};
m.Ic=function(a){return Jc[a]||(Jc[a]=0<=m.Ia(Kc,a))};m.Lc=function(a){return m.D&&(Cc()||m.Mc>=a)};m.E=function(a){return m.ka(a)?window.document.getElementById(a):a};m.Nc=function(a){return m.ka(a)?window.document.getElementById(a):a};m.F=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=m.Oc("*",a,b)[0];return d||null};
m.Oc=function(a,b,c){var d=window.document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},e=0,f=0,h;h=c[f];f++)a==h.nodeName&&(d[e++]=h);d.length=e;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(f=e=0;h=c[f];f++)a=h.className,"function"==typeof a.split&&m.Ra(a.split(/\s+/),b)&&(d[e++]=h);d.length=e;return d}return c};
m.Pc=function(a,b){m.Cb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Qc?a.setAttribute(Qc[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})};m.Rc=function(a){var b=m.Sc(a);a=a.parentWindow||a.defaultView;return m.D&&m.Ic("10")&&a.pageYOffset!=b.scrollTop?new m.wc(b.scrollLeft,b.scrollTop):new m.wc(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
m.Sc=function(a){return!m.Gc&&m.Tc(a)?a.documentElement:a.body||a.documentElement};m.Uc=function(a,b,c){return m.Vc(window.document,arguments)};m.Vc=function(a,b){var c=b[0],d=b[1];if(!Wc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',m.ya(d.name),'"');if(d.type){c.push(' type="',m.ya(d.type),'"');var e={};m.Jb(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(m.ka(d)?c.className=d:m.ia(d)?c.className=d.join(" "):m.Pc(c,d));2<b.length&&m.Xc(a,c,b,2);return c};
m.Xc=function(a,b,c,d){function e(c){c&&b.appendChild(m.ka(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];!m.ja(f)||m.oa(f)&&0<f.nodeType?e(f):(0,m.A)(Yc(f)?m.Wa(f):f,e)}};m.Tc=function(a){return"CSS1Compat"==a.compatMode};m.Zc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};m.$c=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};m.ad=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
var bd=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};var cd=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
m.dd=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};m.ed=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};var Yc=function(a){if(a&&"number"==typeof a.length){if(m.oa(a))return"function"==typeof a.item||"string"==typeof a.item;if(m.na(a))return"function"==typeof a.item}return!1};
m.fd=function(a,b,c,d){c||(a=a.parentNode);c=null==d;for(var e=0;a&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return null};m.gd=function(a){return function(){return a}};m.hd=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};m.id=function(){};
m.jd=function(a){if(a instanceof m.id)return a;if("function"==typeof a.Ib)return a.Ib(!1);if(m.ja(a)){var b=0,c=new m.id;c.next=function(){for(;;){if(b>=a.length)throw m.kd;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");};m.ld=function(a,b,c){if(m.ja(a))try{(0,m.A)(a,b,c)}catch(d){if(d!==m.kd)throw d;}else{a=m.jd(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(e){if(e!==m.kd)throw e;}}};
m.md=function(a){if(m.ja(a))return m.Wa(a);a=m.jd(a);var b=[];m.ld(a,function(a){b.push(a)});return b};m.nd=function(a,b,c,d,e,f,h){var k="";a&&(k+=a+":");c&&(k+="//",b&&(k+=b+"@"),k+=c,d&&(k+=":"+d));e&&(k+=e);f&&(k+="?"+f);h&&(k+="#"+h);return k};m.od=function(a){if(pd){pd=!1;var b=m.ea.location;if(b){var c=b.href;if(c&&(c=m.qd(c))&&c!=b.hostname)throw pd=!0,Error();}}return a.match(rd)};m.sd=function(a){return a?(0,window.decodeURI)(a):a};m.qd=function(a){return m.sd(m.od(a)[3]||null)};
m.td=function(a){a=m.od(a);return m.nd(null,null,null,null,a[5],a[6],a[7])};m.ud=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};m.vd=function(a,b,c){if(m.ia(b))for(var d=0;d<b.length;d++)m.vd(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",m.xa(b))};var wd=function(a,b){for(var c in b)m.vd(c,b[c],a);return a};m.xd=function(a){a=wd([],a);a[0]="";return a.join("")};
m.yd=function(a,b){return m.ud(wd([a],b))};m.zd=function(a,b,c){a&&(c?a&&(a=m.Uc("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),m.ed(a).body.appendChild(a)):Ad(a,b))};var Ad=function(a,b){var c=new window.Image,d=""+Bd++;Cd[d]=c;c.onload=c.onerror=function(){b&&Cd[d]&&b();delete Cd[d]};c.src=a;c=eval("null")};m.Dd=function(a,b){this.version=a;this.args=b};m.Ed=function(a,b){this.j=a;this.Qh=b};
m.Fd=function(a,b){var c=m.Gd();c&&c.publish.call(c,a.toString(),a,b)};m.Gd=function(){return m.n("yt.pubsub2.instance_")};var Hd=function(a){m.Dd.call(this,1,arguments)};m.Id=function(a,b,c){Jd(c)[a]=b||(0,m.G)();b||Kd(a);m.w("CSI_LOG_ON_TICK")&&Ld(!1,c)};var Md=function(a,b){Nd(void 0).yt_sts=a;m.Id("_start",b,void 0)};var Od=function(a){Pd(a);Qd();m.l("yt.timing.pingSent_",!1,void 0)};
var Rd=function(a){a=Jd(a);if(a.aft)return a.aft;for(var b=m.w("TIMING_AFT_KEYS",["ol"]),c=b.length,d=0;d<c;d++){var e=a[b[d]];if(e)return e}return window.NaN};
var Sd=function(a,b){var c=Td(b).span,d;d=a.redirectEnd-a.redirectStart;0<d&&(c.rtime_=d);d=a.domainLookupEnd-a.domainLookupStart;0<d&&(c.dns_=d);d=a.connectEnd-a.connectStart;0<d&&(c.tcp_=d);d=a.connectEnd-a.secureConnectionStart;a.secureConnectionStart>=a.navigationStart&&0<d&&(c.stcp_=d);d=a.responseStart-a.requestStart;0<d&&(c.req_=d);d=a.responseEnd-a.responseStart;0<d&&(c.rcv_=d)};var Ud=function(a){return Math.round(Vd.timing.navigationStart+a)};
var Wd=function(a){var b=window.location.protocol,c=Vd.getEntriesByType("resource"),d=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.googleapis.com/css?family=")})[0],c=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});d&&0<d.startTime&&0<d.responseEnd&&(a.wfcs=Ud(d.startTime),a.wfce=Ud(d.responseEnd));c&&0<c.startTime&&0<c.responseEnd&&(a.wffs=Ud(c.startTime),a.wffe=Ud(c.responseEnd))};
var Xd=function(a){var b=Jd(a),c=Td(a).span,d=Nd(a),e=m.n("yt.timing.reportbuilder_");if(e){if(e=e(b,c,d,a))Yd(e),Od(a)}else{e={v:2,s:m.w("CSI_SERVICE_NAME","youtube"),action:m.w("TIMING_ACTION")};if(Vd.now&&Vd.timing){var f=Vd.timing.navigationStart+Vd.now(),f=Math.round((0,m.G)()-f);d.yt_hrd=f}var f=m.w("TIMING_INFO")||{},h;for(h in f)d[h]=f[h];h=d.srt;delete d.srt;var k;h||0===h||(k=Vd.timing||{},h=Math.max(0,k.responseStart-k.navigationStart),(0,window.isNaN)(h)&&d.pt&&(h=d.pt));if(h||0===h)d.srt=
h;d.h5jse&&(f=window.location.protocol+m.n("ytplayer.config.assets.js"),(f=Vd.getEntriesByName?Vd.getEntriesByName(f)[0]:null)?d.h5jse=Math.round(d.h5jse-f.responseEnd):delete d.h5jse);b.aft=Rd(a);f=b._start;if("cold"==d.yt_lt){k||(k=Vd.timing||{});var p;t:if(p=k,p.msFirstPaint)p=Math.max(0,p.msFirstPaint);else{var v=window.chrome;if(v&&(v=v.loadTimes,m.na(v))){var v=v(),x=1E3*Math.min(v.requestTime||window.Infinity,v.startLoadTime||window.Infinity),x=window.Infinity===x?0:p.navigationStart-x;p=Math.max(0,
Math.round(1E3*v.firstPaintTime+x)||0);break t}p=0}0<p&&p>f&&(b.fpt=p);Sd(k,a);m.w("EXP_WEBFONT_ENABLED")&&Vd.getEntriesByType&&Wd(b)}d.p=m.w("CLIENT_PROTOCOL")||"unknown";d.t=m.w("CLIENT_TRANSPORT")||"unknown";for(var O in d)"_"!=O.charAt(0)&&(e[O]=d[O]);m.w("CSI_MORE")&&(b.ps=(0,m.G)());d={};k=[];for(var ca in b)"_"!=ca.charAt(0)&&(p=Math.max(Math.round(b[ca]-f),0),d[ca]=p,k.push(ca+"."+p));e.rt=k.join(",");b={};ca=[];for(var ma in c)"_"!=ma.charAt(0)&&(b[ma]=c[ma],ca.push(ma+"."+c[ma]));e.it=ca.join(",");
(c=m.n("ytdebug.logTiming"))&&c(e,d,b);Od(a);m.w("EXP_DEFER_CSI_PING")?(Zd(),m.l("yt.timing.deferredPingArgs_",e,void 0),a=m.y(Zd,0),m.l("yt.timing.deferredPingTimer_",a,void 0)):Yd(e);m.Fd($d,new Hd(d.aft+(h||0)))}};var Ld=function(a,b){var c=m.w("TIMING_ACTION"),d=Jd(b);if(c&&d._start&&Rd(b)){var c=!0,e=m.w("TIMING_WAIT",[]);if(!a&&e.length)for(var f=0,h=e.length;f<h;++f)if(!(e[f]in d)){c=!1;break}(c||b)&&Xd(b)}};var ae=function(a){m.w("CSI_LOG_ON_TICK")||Ld(!1,a)};
var Yd=function(a){m.w("EXP_DEFER_CSI_PING")&&(m.fb(m.n("yt.timing.deferredPingTimer_")),m.l("yt.timing.deferredPingArgs_",null,void 0));var b="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c="",d;for(d in a)c+="&"+d+"="+a[d];m.zd(b+"?"+c.substring(1));m.l("yt.timing.pingSent_",!0,void 0)};var Zd=function(a){if(m.w("EXP_DEFER_CSI_PING")){var b=m.n("yt.timing.deferredPingArgs_");b&&(a&&(b.yt_fss=a),Yd(b))}};var Jd=function(a){return Td(a).tick};var Nd=function(a){return Td(a).info};
var Td=function(a){return m.n("ytcsi."+(a||"")+"data_")||Pd(a)};var Pd=function(a){var b={tick:{},span:{},info:{}};m.l("ytcsi."+(a||"")+"data_",b,void 0);return b};var be=function(a){m.w("CSI_MORE")&&!m.n("yt.timing.pingSent_")&&(Nd(void 0).ap=1,Nd(void 0).yt_fss=a,Xd())};var ce=function(a){a=m.de(a);return m.ee(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
m.ee=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};m.de=function(a){a=(0,m.fe)(a);return null===a?null:a.split(".").reverse()};m.ge=function(a,b){m.zd("/gen_204?"+a,b)};m.he=function(a){if(a.classList)return a.classList;a=a.className;return m.ka(a)&&a.match(/\S+/g)||[]};m.H=function(a,b){return a.classList?a.classList.contains(b):m.Ra(m.he(a),b)};m.I=function(a,b){a.classList?a.classList.add(b):m.H(a,b)||(a.className+=0<a.className.length?" "+b:b)};
m.J=function(a,b){a.classList?a.classList.remove(b):m.H(a,b)&&(a.className=(0,m.ie)(m.he(a),function(a){return a!=b}).join(" "))};m.je=function(a,b,c){c?m.I(a,b):m.J(a,b)};
var ke=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||m.Ib(le);this.assets=a.assets||{};this.attrs=a.attrs||m.Ib(me);this.params=a.params||m.Ib(ne);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};m.oe=function(a){a instanceof ke||(a=new ke(a));return a};var pe=function(){return null!=m.qe};
m.re=function(){return m.qe?m.qe.invoke():null};m.se=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,m.A)(a.childNodes,function(a){b.appendChild(m.se(a))}):b.innerHTML=a.innerHTML;return b};
m.te=function(a){if(a=a||window.event){for(var b in a)b in ue||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;this.Wa=a;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:
a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;"MozMousePixelScroll"==this.type?(this.wheelDeltaX=a.axis==a.HORIZONTAL_AXIS?a.detail:0,this.wheelDeltaY=a.axis==a.HORIZONTAL_AXIS?0:a.detail):window.opera?(this.wheelDeltaX=0,this.wheelDeltaY=a.detail):0==a.wheelDelta%120?"WebkitTransform"in window.document.documentElement.style?window.chrome&&0==window.navigator.platform.indexOf("Mac")?(this.wheelDeltaX=a.wheelDeltaX/
-30,this.wheelDeltaY=a.wheelDeltaY/-30):(this.wheelDeltaX=a.wheelDeltaX/-1.2,this.wheelDeltaY=a.wheelDeltaY/-1.2):(this.wheelDeltaX=0,this.wheelDeltaY=a.wheelDelta/-1.6):(this.wheelDeltaX=a.wheelDeltaX/-3,this.wheelDeltaY=a.wheelDeltaY/-3);this.Uk=a.pageX;this.Vk=a.pageY}};m.ve=function(a,b,c,d){return m.Eb(m.we,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
m.K=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=m.ve(a,b,c,d);if(e)return e;var e=++xe.count+"",f=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),h;h=f?function(d){d=new m.te(d);if(!m.fd(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new m.te(b);b.currentTarget=a;return c.call(a,b)};h=m.db(h);m.we[e]=[a,b,c,h,d];a.addEventListener?"mouseenter"==b&&f?a.addEventListener("mouseover",
h,d):"mouseleave"==b&&f?a.addEventListener("mouseout",h,d):"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style?a.addEventListener("MozMousePixelScroll",h,d):a.addEventListener(b,h,d):a.attachEvent("on"+b,h);return e};m.L=function(a){a&&("string"==typeof a&&(a=[a]),(0,m.A)(a,function(a){if(a in m.we){var c=m.we[a],d=c[0],e=c[1],f=c[3],c=c[4];d.removeEventListener?d.removeEventListener(e,f,c):d.detachEvent&&d.detachEvent("on"+e,f);delete m.we[a]}}))};
m.ye=function(a){a=a||window.event;a=a.target||a.srcElement;3==a.nodeType&&(a=a.parentNode);return a};m.ze=function(a){this.j=a};m.Ae=function(a){a=(a.j.cookie||"").split(m.Be);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};m.Ce=function(a,b,c,d){m.De.set(""+a,b,c,"/",d||"youtube.com")};m.Ee=function(a,b){return m.De.get(""+a,b)};
m.Fe=function(a,b){a=!!a;m.l("_lactCookie",a,window);if(null==m.n("_lact",window)){if(m.w("EXP_LACT_TEMPDATA")){var c=(0,window.parseInt)(m.w("LACT"),10),c=(0,window.isFinite)(c)?(0,m.G)()-Math.max(c,0):-1;m.l("_lact",c,window);-1==c&&Ge()}else a&&b?(c=m.Ee("ACTIVITY","-1"),m.l("_lact",(0,window.parseInt)(c,10),window)):(m.l("_lact",-1,window),Ge());m.K(window.document,"keydown",Ge);m.K(window.document,"keyup",Ge);m.K(window.document,"mousedown",Ge);m.K(window.document,"mouseup",Ge);m.w("EXP_LACT_MOUSE")&&
m.z("page-mouse",Ge);m.w("EXP_LACT_SCROLL")&&m.z("page-scroll",Ge);m.w("EXP_LACT_RESIZE")&&m.z("page-resize",Ge)}};var Ge=function(){var a=m.n("_lact",window);null==a&&(m.Fe(),a=m.n("_lact",window));var b=(0,m.G)();m.l("_lact",b,window);m.w("EXP_LACT_TEMPDATA")||m.n("_lactCookie",window)&&1E3<=b-a&&m.Ce("ACTIVITY",""+b,-1);m.B("USER_ACTIVE")};m.He=function(){var a=m.n("_lact",window);return null==a?-1:Math.max((0,m.G)()-a,0)};
m.Ie=function(a,b,c){var d=m.qd(a);if(d==m.qd(window.location.href)||!d&&0==a.lastIndexOf("/",0))if(a=m.td(a),d=a.indexOf("#"),a=0>d?a:a.substr(0,d))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&Je(a,b,c)):Je(a,b)};var Je=function(a,b,c){a=m.w("SMALLER_SESSION_TEMPDATA_NAME")?"ST-"+Ma(a).toString(36):"s_tempdata-"+Ma(a);c=c||5;b=b?m.xd(b):"";m.Ce(a,b,c)};m.Ke=function(a,b,c){var d=c||"";c=window.location;a=m.yd(a,b||{})+d;a=a instanceof m.Tb?a:m.Wb(a);c.href=m.Vb(a)};
m.Le=function(a,b){b&&m.Ie(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):m.Ke(a)};m.Me=function(a,b,c){var d=m.w("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&m.Ie(a,b);if(c)return!1;m.Le(a);return!0};var Ne=function(a,b,c){this.A=c;this.l=a;this.n=b;this.k=0;this.j=null};var Oe=function(a){m.ea.setTimeout(function(){throw a;},0)};
var Pe=function(){var a=m.ea.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!m.xc("Presto")&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,m.q)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!Ac()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(m.da(c.next)){c=c.next;var a=c.Bm;c.Bm=null;a()}};return function(a){d.next={Bm:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")?function(a){var b=window.document.createElement("script");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){m.ea.setTimeout(a,0)}};var Qe=function(){this.k=this.j=null};var Re=function(){this.next=this.scope=this.Od=null};var Se=function(a,b){Te||Ue();Ve||(Te(),Ve=!0);We.add(a,b)};
var Ue=function(){if(m.ea.Promise&&m.ea.Promise.resolve){var a=m.ea.Promise.resolve();Te=function(){a.then(Ze)}}else Te=function(){var a=Ze;!m.na(m.ea.setImmediate)||m.ea.Window&&m.ea.Window.prototype&&m.ea.Window.prototype.setImmediate==m.ea.setImmediate?($e||($e=Pe()),$e(a)):m.ea.setImmediate(a)}};var Ze=function(){for(var a=null;a=We.remove();){try{a.Od.call(a.scope)}catch(b){Oe(b)}af.put(a)}Ve=!1};m.bf=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};
m.cf=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};m.df=function(a,b){this.j=0;this.C=void 0;this.n=this.k=this.l=null;this.A=this.B=!1;if(a==m.ef)ff(this,2,b);else try{var c=this;a.call(b,function(a){ff(c,2,a)},function(a){ff(c,3,a)})}catch(d){ff(this,3,d)}};var gf=function(){this.next=this.context=this.k=this.l=this.j=null;this.n=!1};var hf=function(a,b,c){var d=jf.get();d.l=a;d.k=b;d.context=c;return d};m.ef=function(){};
m.kf=function(a,b,c,d){a instanceof m.df?lf(a,hf(b||m.fa,c||null,d)):a.then(b,c,d)};var mf=function(a,b){if(0==a.j)if(a.l){var c=a.l;if(c.k){for(var d=0,e=null,f=null,h=c.k;h&&(h.n||(d++,h.j==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.j&&1==d?mf(c,b):(f?(d=f,d.next==c.n&&(c.n=d),d.next=d.next.next):nf(c),of(c,e,3,b)))}a.l=null}else ff(a,3,b)};var lf=function(a,b){a.k||2!=a.j&&3!=a.j||pf(a);a.n?a.n.next=b:a.k=b;a.n=b};
m.qf=function(a,b,c,d){var e=hf(null,null,null);e.j=new m.df(function(a,h){e.l=b?function(c){try{var e=b.call(d,c);a(e)}catch(v){h(v)}}:a;e.k=c?function(b){try{var e=c.call(d,b);!m.da(e)&&b instanceof rf?h(b):a(e)}catch(v){h(v)}}:h});e.j.l=a;lf(a,e);return e.j};
var ff=function(a,b,c){if(0==a.j){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(m.cf(c)){a.j=1;m.kf(c,a.J,a.F,a);return}if(m.oa(c))try{var d=c.then;if(m.na(d)){sf(a,c,d);return}}catch(e){b=3,c=e}}a.C=c;a.j=b;a.l=null;pf(a);3!=b||c instanceof rf||tf(a,c)}};var sf=function(a,b,c){function d(b){f||(f=!0,a.F(b))}function e(b){f||(f=!0,a.J(b))}a.j=1;var f=!1;try{c.call(b,e,d)}catch(h){d(h)}};var pf=function(a){a.B||(a.B=!0,Se(a.P,a))};
var nf=function(a){var b=null;a.k&&(b=a.k,a.k=b.next,b.next=null);a.k||(a.n=null);return b};var of=function(a,b,c,d){b.j&&(b.j.l=null);if(2==c)b.l.call(b.context,d);else if(null!=b.k){if(!b.n)for(;a&&a.A;a=a.l)a.A=!1;b.k.call(b.context,d)}jf.put(b)};var tf=function(a,b){a.A=!0;Se(function(){a.A&&uf.call(null,b)})};var rf=function(a){m.wa.call(this,a)};var vf=function(a){this.j=a;a.then((0,m.q)(function(){},this))};
var wf=function(a,b,c,d){for(var e=Array(arguments.length-3),f=3;f<arguments.length;f++)e[f-3]=arguments[f];f=xf(a,b,c).then(function(a){return a.apply(this,e)});return new vf(f)};
var xf=function(a,b,c){var d="https://www.gstatic.com/feedback/js/help/"+(a&&"prod"!=a&&"canary"!=a?"nonprod":"prod")+"/"+b;if(a=yf[c])return a;a=(a=m.n(c))?new m.df(m.ef,a):(new m.df(function(a,b){var c=window.document.createElement("script");c.async=!0;c.src=d;c.onload=c.onreadystatechange=function(){c.readyState&&"loaded"!=c.readyState&&"complete"!=c.readyState||a()};c.onerror=b;(window.document.head||window.document.getElementsByTagName("head")[0]).appendChild(c)})).then(function(){var a=m.n(c);
if(!a)throw Error("Failed to load "+c+" from "+d);return a});return yf[c]=a};var zf=function(a,b,c){a.j.then(function(a){var e=a[b];if(!e)throw Error("Method not found: "+b);return e.apply(a,c)})};var Af=function(a){this.j=a};
var Bf=function(a,b){var c=b||{},c=wf("prod","service/lazy.min.js","help.service.Lazy.create",a,{apiKey:c.uf||c.apiKey,environment:c.Ff||c.environment,helpCenterPath:c.aF||c.helpCenterPath,locale:c.locale||c.locale,productData:c.lF||c.productData,receiverUri:c.mF||c.receiverUri,theme:c.theme||c.theme,window:c.window||c.window});return new Af(c)};var Cf=function(a){a=a.match(/[\d]+/g);if(!a)return"";a.length=3;return a.join(".")};var Df=function(a){return(a=a.exec(m.yc))?a[1]:""};
var Ef=function(){this.l=this.k=this.j=0;this.n="";var a=m.n("window.navigator.plugins"),b=m.n("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,f=c.length;e<f;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.n=b;b=a;this.j=b[0];this.k=b[1];this.l=b[2];if(0>=this.j){var h,k,p,v;if(m.Ff)try{h=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(x){h=null}else p=window.document.body,v=window.document.createElement("object"),v.setAttribute("type","application/x-shockwave-flash"),h=p.appendChild(v);if(h&&"GetVariable"in h)try{k=h.GetVariable("$version")}catch(O){k=""}p&&v&&p.removeChild(v);(h=k||"")?(h=h.split(" ")[1].split(","),
h=[(0,window.parseInt)(h[0],10)||0,(0,window.parseInt)(h[1],10)||0,(0,window.parseInt)(h[2],10)||0]):h=[0,0,0];this.j=h[0];this.k=h[1];this.l=h[2]}};var Gf=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.j>b[0]||a.j==b[0]&&a.k>b[1]||a.j==b[0]&&a.k==b[1]&&a.l>=b[2]};
var Hf=function(a){return-1<a.n.indexOf("Gnash")&&-1==a.n.indexOf("AVM2")||9==a.j&&1==a.k||9==a.j&&0==a.k&&1==a.l?!1:9<=a.j};var If=function(a){return m.Jf?!Gf(a,11,2):m.Kf?!Gf(a,11,3):!Hf(a)};m.Lf=function(){return m.Gc?"Webkit":m.Fc?"Moz":m.D?"ms":m.Mf?"O":null};m.Nf=function(){return m.Gc?"-webkit":m.Fc?"-moz":m.D?"-ms":m.Mf?"-o":null};m.Of=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
m.Pf=function(a,b){return a&&b?b instanceof m.Of?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};m.Qf=function(a,b){var c=Rf[b];if(!c){var d=m.Na(b),c=d;void 0===a.style[d]&&(d=m.Lf()+m.Oa(d),void 0!==a.style[d]&&(c=d));Rf[b]=c}return c};m.Sf=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};m.Tf=function(a,b){a.style.height=m.Sf(b,!0)};m.Uf=function(a,b){a.style.display=b?"":"none"};
m.Vf=function(a,b){(a=m.E(a))&&a.style&&(m.Uf(a,b),m.je(a,"hid",!b))};m.M=function(a){(0,m.A)(arguments,function(a){m.Vf(a,!0)})};
var Wf=function(a,b){var c=m.w("FEEDBACK_LOCALE_LANGUAGE"),d=m.Xf,e=m.w("FEEDBACK_LOCALE_EXTRAS",{});a?m.Jb(d,a):m.Jb(d,e);try{var f,h=m.n("yt.player.getPlayerByElement");(f=h?h("player-api"):null)&&f.pauseVideo&&f.pauseVideo();var k=Ef.getInstance();d.flashVersion=k.getVersion().join(".");f&&(d.playback_id=f.getVideoData().cpn)}catch(p){}b&&m.Jb(d,{trackingParam:b});return{helpCenterPath:"/youtube",locale:c,productData:d}};
var Yf=function(){var a=m.w("SESSION_INDEX"),b=m.w("FEEDBACK_BUCKET_ID"),c={abuseLink:"https://support.google.com/youtube/bin/answer.py?answer=140536",customZIndex:"2000000005"};a&&(c.authuser=a+"");b&&(c.bucket=b);return c};m.Zf=function(a,b){try{var c=(a||"59")+"",d=Wf(b),e=Yf();Bf(c,d).l(e);return!1}catch(f){return!0}};
m.$f=function(a,b,c,d,e,f,h,k){b=(b||"59")+"";d=Wf(d,h);a={context:c,anchor:a,enableSendFeedback:f?!1:!0,defaultHelpArticleId:k};m.Jb(a,Yf());try{var p=Bf(b,d);if(e&&!ag)try{p.k(a),ag=!0}catch(v){}p.n(a);return!1}catch(x){return!0}};m.bg=function(a,b,c,d){return m.$f(void 0,d,b,c,void 0,void 0,void 0,a)};m.cg=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.gf=!1;this.Op=!0};
m.dg=function(a,b){m.cg.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.Wa=this.state=null;a&&this.init(a,b)};m.eg=function(a){return!(!a||!a[m.fg])};var gg=function(a,b,c,d,e){this.bf=a;this.j=null;this.src=b;this.type=c;this.Lh=!!d;this.bd=e;this.key=++hg;this.eg=this.Jh=!1};
m.ig=function(a){a.eg=!0;a.bf=null;a.j=null;a.src=null;a.bd=null};m.jg=function(a){this.src=a;this.j={};this.k=0};m.kg=function(a,b){var c=b.type;if(!(c in a.j))return!1;var d=m.Ta(a.j[c],b);d&&(m.ig(b),0==a.j[c].length&&(delete a.j[c],a.k--));return d};m.lg=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.eg&&f.bf==b&&f.Lh==!!c&&f.bd==d)return e}return-1};
m.mg=function(a,b,c,d,e){if(m.ia(b)){for(var f=0;f<b.length;f++)m.mg(a,b[f],c,d,e);return null}c=m.ng(c);return m.eg(a)?a.Q(b,c,d,e):m.og(a,b,c,!1,d,e)};m.og=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=!!e,k=m.pg(a);k||(a[qg]=k=new m.jg(a));c=k.add(b,c,d,e,f);if(c.j)return c;d=rg();c.j=d;d.src=a;d.bf=c;a.addEventListener?a.addEventListener(b.toString(),d,h):a.attachEvent(sg(b.toString()),d);tg++;return c};
var rg=function(){var a=ug,b=vg?function(c){return a.call(b.src,b.bf,c)}:function(c){c=a.call(b.src,b.bf,c);if(!c)return c};return b};m.wg=function(a){if(m.la(a)||!a||a.eg)return!1;var b=a.src;if(m.eg(b))return b.Bq(a);var c=a.type,d=a.j;b.removeEventListener?b.removeEventListener(c,d,a.Lh):b.detachEvent&&b.detachEvent(sg(c),d);tg--;(c=m.pg(b))?(m.kg(c,a),0==c.k&&(c.src=null,b[qg]=null)):m.ig(a);return!0};var sg=function(a){return a in xg?xg[a]:xg[a]="on"+a};
var yg=function(a,b,c,d){var e=!0;if(a=m.pg(a))if(b=a.j[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Lh==c&&!f.eg&&(f=zg(f,d),e=e&&!1!==f)}return e};var zg=function(a,b){var c=a.bf,d=a.bd||a.src;a.Jh&&m.wg(a);return c.call(d,b)};
var ug=function(a,b){if(a.eg)return!0;if(!vg){var c=b||m.n("window.event"),d=new m.dg(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){t:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break t}catch(h){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.currentTarget;f;f=f.parentNode)c.push(f);for(var f=a.type,k=c.length-1;!d.gf&&0<=k;k--){d.currentTarget=c[k];var p=yg(c[k],f,!0,d),e=e&&p}for(k=0;!d.gf&&k<c.length;k++)d.currentTarget=c[k],p=yg(c[k],f,!1,d),e=e&&p}return e}return zg(a,
new m.dg(b,this))};m.pg=function(a){a=a[qg];return a instanceof m.jg?a:null};m.ng=function(a){if(m.na(a))return a;a[Ag]||(a[Ag]=function(b){return a.handleEvent(b)});return a[Ag]};m.Bg=function(){var a=m.Ee("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(m.Cg[d]=c.toString())}};var Dg=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};
var Eg=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};m.Fg=function(a){a=void 0!==m.Cg[a]?m.Cg[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};m.Gg=function(a,b){return!!((m.Fg("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
var Hg=function(a,b,c){if(b){a=m.ka(a)?m.Nc(a):a;c=m.oe(c);var d=m.Ib(c.attrs);d.tabindex=0;var e=m.Ib(c.params);e.flashvars=m.xd(c.args);if(m.Ff){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var f in d)b.setAttribute(f,d[f]);for(f in e)d=window.document.createElement("param"),d.setAttribute("name",f),d.setAttribute("value",e[f]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");
b.setAttribute("name",d.id);for(f in d)b.setAttribute(f,d[f]);for(f in e)b.setAttribute(f,e[f])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};m.Ig=function(a,b){a=m.ka(a)?m.Nc(a):a;b=m.oe(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=Ef.getInstance();Gf(c,b.minVersion)?(c=Jg(b,c),Hg(a,c,b)):Kg(a,b,c)};
var Lg=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=m.oe(a);var d=!!b,e=m.E(a.attrs.id),f=e?e.parentNode:null;if(e&&f){if(window!=window.top){var h=null;if(window.document.referrer){var k=window.document.referrer.substring(0,128);ce(k)||(h=k)}else h="unknown";h&&(d=!0,a.args.framer=h)}h=Ef.getInstance();if(Gf(h,a.minVersion)){var k=Jg(a,h),p="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(p=e.getAttribute("src")||e.movie);(p!=k||d)&&Hg(f,k,a);If(h)&&Mg()}else Kg(f,a,h);c&&c()}else m.y(function(){Lg(a,
b,c)},50)}};var Kg=function(a,b,c){0==c.j&&b.fallback?b.fallback():0==c.j&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+m.kb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};var Jg=function(a,b){var c;(c=Hf(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Gf(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.url};
var Mg=function(){var a=m.E("flash10-promo-div"),b=m.Gg(m.Bg.getInstance(),107);a&&!b&&m.M(a)};m.Ng=function(a,b){var c=a.match(Og);window.spf.style.load(a,c?c[1]:"",b)};var Pg=function(){if(2.2==Qg)return!0;var a;a=m.n("yt.player.utils.videoElement_");a||(a=window.document.createElement("video"),m.l("yt.player.utils.videoElement_",a,void 0));try{return!(!a||!a.canPlayType||!a.canPlayType('video/mp4; codecs="avc1.42001E, mp4a.40.2"')&&!a.canPlayType('video/webm; codecs="vp8.0, vorbis"'))}catch(b){return!1}};
var Rg=function(){};m.Sg=function(){};m.Tg=function(a){this.j=a};m.Ug=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.j=a};var Vg=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.j=a};
m.Wg=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};m.Xg=function(a){return(new m.Yg(void 0)).Gb(a)};m.Yg=function(a){this.j=a};
var Zg=function(a,b,c){switch(typeof b){case "string":$g(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(m.ia(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],Zg(a,a.j?a.j.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&
(c.push(d),$g(f,c),c.push(":"),Zg(a,a.j?a.j.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}};var $g=function(a,b){b.push('"',a.replace(ah,function(a){if(a in bh)return bh[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return bh[a]=e+b.toString(16)}),'"')};m.ch=function(a){this.j=a};var dh=function(a){this.j=a};var eh=function(a){this.data=a};var fh=function(a){return!m.da(a)||a instanceof eh?a:new eh(a)};
m.gh=function(a){this.j=a};m.hh=function(a){var b=a.creation;a=a.expiration;return!!a&&a<(0,m.G)()||!!b&&b>(0,m.G)()};m.ih=function(a){this.j=a};m.jh=function(a,b,c){var d=c&&0<c?c:0;c=d?(0,m.G)()+1E3*d:0;if((d=d?m.kh:m.lh)&&window.JSON){m.ka(b)||(b=JSON.stringify(b,void 0));try{d.set(a,b,c)}catch(e){d.remove(a)}}};m.mh=function(a){if(!m.lh&&!m.kh||!window.JSON)return null;var b;try{b=m.lh.get(a)}catch(c){}if(!m.ka(b))try{b=m.kh.get(a)}catch(d){}if(!m.ka(b))return null;try{b=JSON.parse(b,void 0)}catch(e){}return b};
var nh=function(){var a={volume:100,muted:!1},b=m.mh("yt-player-volume")||{};a.volume=(0,window.isNaN)(b.volume)?100:m.vc(b.volume,0,100);a.muted=void 0==b.muted?!1:b.muted;return a};
var oh=function(a,b){m.u.call(this);this.n=this.B=a;this.R=b;this.P=!1;this.k={};this.bb=this.O=null;this.sa=new m.$a;m.Xa(this,this.sa);this.A={};this.J=this.gb=this.l=this.Hb=this.j=null;this.Ga=!1;this.S=this.F=this.wb=this.C=null;this.ib={};this.Bd=["onReady"];this.nb=[];this.Nb=null;this.pc=0;this.Pa={};ph(this);this.yd("onVolumeChange",(0,m.q)(this.wy,this));this.yd("onError",(0,m.q)(this.uy,this));this.yd("onTabOrderChange",(0,m.q)(this.os,this));this.yd("onTabAnnounce",(0,m.q)(this.IA,this));
this.yd("WATCH_LATER_VIDEO_ADDED",(0,m.q)(this.xy,this));this.yd("WATCH_LATER_VIDEO_REMOVED",(0,m.q)(this.yy,this));this.yd("onMouseWheelCapture",(0,m.q)(this.ky,this));this.yd("onMouseWheelRelease",(0,m.q)(this.ly,this));this.yd("onMouseMoveCapture",(0,m.q)(this.iy,this));this.Bb=!1;this.Pc=m.qh||m.rh;this.Ra=this.U=null;m.mg(this.B,"mousewheel",this.bp,!1,this);m.mg(this.B,"wheel",this.bp,!1,this)};
var sh=function(a,b){a.Hb=b;a.j=b.clone();a.l=a.j.attrs.id||a.l;"video-player"==a.l&&(a.l=a.R,a.j.attrs.id=a.R);a.n.id==a.l&&(a.l=a.l+"-player",a.j.attrs.id=a.l);a.j.args.enablejsapi="1";a.j.args.playerapiid=a.R;a.gb||(a.gb=th(a,a.j.args.jsapicallback||"onYouTubePlayerReady"));a.j.args.jsapicallback=null;var c=a.j.attrs.width;c&&(a.n.style.width=m.Sf(Number(c)||c,!0));(c=a.j.attrs.height)&&m.Tf(a.n,Number(c)||c);a.n.style.overflow="hidden"};
var uh=function(a){a.j.loaded||(a.j.loaded=!0,"0"!=a.j.args.autoplay?a.k.loadVideoByPlayerVars(a.j.args):a.k.cueVideoByPlayerVars(a.j.args))};var vh=function(a){if(!m.da(a.j.disable.flash)){var b=a.j.disable,c;c=Gf(Ef.getInstance(),a.j.minVersion);b.flash=!c}return!a.j.disable.flash};
var wh=function(a){var b=xh(a);b&&b.stopVideo&&b.stopVideo();if(vh(a)){var c=a.j;b&&b.getUpdatedConfigurationData&&(c=m.oe(b.getUpdatedConfigurationData()));c.args.autoplay=1;c.args.html5_unavailable="1";sh(a,c);yh(a,"flash")}};
var yh=function(a,b){if(!a.Oa()){if(!b){var c;if(!(c=!a.j.html5&&vh(a))){if(!m.da(a.j.disable.html5)){if(c=Pg())c=zh(a)||a.j.assets.js;a.j.disable.html5=!c;c||(a.j.args.html5_unavailable="1")}c=!!a.j.disable.html5}b=c?vh(a)?"flash":"unsupported":"html5"}("flash"==b?a.bB:"html5"==b?a.cB:a.dB).call(a)}};var zh=function(a){var b=!0,c=xh(a);c&&a.j&&(a=a.j,b=m.C(c,"version")==a.assets.js);return b&&!!m.n("yt.player.Application.create")};
var xh=function(a){var b=m.E(a.l);!b&&a.n&&a.n.querySelector&&(b=a.n.querySelector("#"+a.l));return b};var Ah=function(a,b,c){var d=b[c];return function(){try{return a.Nb=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.Nb=e,m.hb(e,"WARNING"))}}};
var ph=function(a){a.P=!1;if(a.bb)for(var b in a.A)a.bb(b,a.A[b]);for(var c in a.Pa)m.fb((0,window.parseInt)(c,10));a.Pa={};a.O=null;a.bb=null;for(var d in a.k)a.k[d]=null;a.k.addEventListener=(0,m.q)(a.yd,a);a.k.removeEventListener=(0,m.q)(a.aA,a);a.k.destroy=(0,m.q)(a.dispose,a);a.k.getLastError=(0,m.q)(a.Ss,a);a.k.getPlayerType=(0,m.q)(a.Ts,a);a.k.getCurrentVideoConfig=(0,m.q)(a.Rs,a);a.k.loadNewVideoConfig=(0,m.q)(a.Ul,a);a.k.isReady=(0,m.q)(a.pB,a)};
var th=function(a,b){var c=b;if("string"==typeof b){if(a.ib[b])return a.ib[b];c=function(){var a=m.n(b);a&&a.apply(m.ea,arguments)};a.ib[b]=c}return c?c:null};var Bh=function(a,b){var c="ytPlayer"+b+a.R;a.A[b]=c;m.ea[c]=function(c){var e=m.y(function(){a.Oa()||(a.sa.W(b,c),m.Gb(a.Pa,e.toString()))},0);m.Hb(a.Pa,e.toString(),!0)};return c};var Ch=function(a){return(a=xh(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
var Dh=function(a){m.Id("dcp");a.cancel();ph(a);a.J=null;a.j&&(a.j.loaded=!1);var b=xh(a);"html5"==Ch(a)?a.wb=b:b&&b.destroy&&b.destroy();m.Zc(a.B);m.L(a.nb);a.nb.length=0;a.F=null;a.S=null};m.Eh=function(a,b){a=m.ka(a)?m.Nc(a):a;b=m.oe(b);var c=Fh+"_"+m.pa(a),d=Gh[c];if(d)return d.Ul(b),d.k;d=new oh(a,c);Gh[c]=d;m.B("player-added",d.k);m.Ya(d,m.r(Hh,d));m.y(function(){d.Ul(b)},0);return d.k};var Ih=function(){for(var a in Gh){var b=Gh[a];b&&b.cancel()}};
m.Jh=function(a){if(a=m.E(a))a=Fh+"_"+m.pa(a),(a=Gh[a])&&a.dispose()};var Hh=function(a){Gh[a.getId()]=null};m.Kh=function(a){a=m.E(a);if(!a)return null;var b=Fh+"_"+m.pa(a),c=Gh[b];c||(c=new oh(a,b),Gh[b]=c);return c.k};m.Lh=function(){return m.H(m.E("page-container"),"remote-connected")};
var Mh=function(){m.l("yt.abuse.botguardInitialized",pe,void 0);m.l("yt.abuse.invokeBotguard",m.re,void 0);m.l("yt.player.exports.navigate",m.Me,void 0);m.l("yt.player.embed",m.Eh,void 0);m.l("yt.player.destroy",m.Jh,void 0);m.l("yt.player.cancelAll",Ih,void 0);m.l("yt.player.getPlayerByElement",m.Kh,void 0);m.l("yt.player.exports.feedbackStart",m.Zf,void 0);m.l("yt.player.exports.feedbackShowArticle",m.bg,void 0);m.l("yt.util.activity.init",m.Fe,void 0);m.l("yt.util.activity.getTimeSinceActive",
m.He,void 0);m.l("yt.util.activity.setTimestamp",Ge,void 0);var a=m.n("ytplayer.config");Nh(a);m.n("ytspf.enabled")&&(Oh=m.eb(Ph,5E3),(a=m.Qh())?(a.addEventListener("onReady",Ph),a.addEventListener("onStateChange",Ph)):Rh("unable to init PP monitor"))};
var Nh=function(a){Ih();if(a=a||null){var b=m.Qh(),c=!0,d=m.Sh;m.Sh=null;b&&b.getVideoData&&d&&(c=b.getVideoData(),c=!!d.fullscreen||c.video_id!=a.args.video_id||c.list!=a.args.list||c.video_id!=d.videoId||c.list!=d.listId);c?(Th="",m.Eh("player-api",a)):b.playVideo();a=m.oe(a);a.loaded=!0}Ph();m.l("ytplayer.config",a,void 0)};m.Qh=function(){var a=m.n("yt.player.getPlayerByElement");return a?a("player-api"):null};
var Ph=function(){var a=m.Qh();if(a){var b;b=m.E("player");b=!b||m.H(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==m.w("PAGE_NAME"),e=m.Lh();!c||d||e||(Rh("PP playing off watch (paused)"),a.pauseVideo());b&&d?Rh("PP off-screen on watch"):b||d||Rh("PP !off-screen off watch")}};var Rh=function(a){var b=m.w("PAGE_NAME");b&&(b=[b,Th,m.n("_spf_state.nav-counter")],a+="("+b.join(",")+")",m.l("yt.www.persistentplayer.issue",a,void 0),m.hb(Error(a),"WARNING"))};
var Uh=function(){m.Id("ol");Vh("init");var a=m.w("PAGE_NAME");a&&Vh("init-"+a);ae()};var Vh=function(a){m.sb()?Wh.push(m.tb(m.r(m.rb,a),0)):m.B(a)};var Xh=function(){m.wb(Wh);Wh.length=0;var a=m.w("PAGE_NAME");a&&m.rb("dispose-"+a);m.rb("dispose")};var Yh=function(){Uh()};var Zh=function(){m.w("TIMING_REPORT_ON_UNLOAD")&&Ld(!0);be("u");Zd("u");Xh()};
var $h=function(a,b,c,d,e){for(var f=window.document.getElementsByTagName("script"),h=!1,k=0,p=f.length;k<p;k++)if(0<f[k].src.indexOf("/debug-")){h=!0;break}h&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),m.hb(e))};var ai=function(){bi=1;ci=0;m.w("TIMING_REPORT_ON_UNLOAD")&&Ld(!0);be("n");Zd("n");Od();m.w("CSI_TRACK_ON_BEGIN")&&Md("nb");Kd("mark_navigation_requested");di(ei);m.rb("navigate")};
var fi=function(a){a=a.detail.part||a.detail.partial;m.Id("nc"+ci);++ci;var b=1==bi;bi=2;b?(di(gi),hi()):di(ii);(a=a.data&&a.data.swfcfg)&&ji(a)};var ki=function(){};var li=function(a){a=a.detail.response;var b=1==bi;bi=3;b&&(di(mi),hi());(a=a.data&&a.data.swfcfg)&&ji(a)};
var ni=function(a){m.Id("nd");a=a.detail.response;m.oi=a.cacheKey;a=a.timing;var b=window._spf_state,b=b&&b["nav-counter"]||0;Nd(void 0).yt_nav=b;Md("ne",a.responseStart);b=Math.max(0,a.responseStart-a.navigationStart);Nd(void 0).srt=b;b=a.spfCached?"hot":"warm";Nd(void 0).yt_lt=b;b=+!!a.spfPrefetched;Nd(void 0).yt_pft=b;b=a.responseStart-a.fetchStart;Td(void 0).span.req=b;"redirectStart"in a&&Sd(a);di(pi);window.document.getElementById("content").style.height="";Uh();bi=0};
var qi=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),m.hb(a)};var ri=function(a){a=m.xd({spfreload:"1",url:a.detail.url,reason:a.detail.reason});m.ge(a)};var si=function(){ti()};var ui=function(){};
var hi=function(){m.w("USE_SPF_SCROLL_POSITION")||window.scroll(0,0);var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");Xh();for(var b in m.cb)delete m.cb[b];m.l("ytplayer.config",null,void 0);if((a=m.Qh())&&a.stopVideo){if(a.stopVideo(),a=a.getLastError())Th=a,(a=m.E("movie_player"))&&a.stopVideo?(a.stopVideo(),Th="recovered"):Th="missing2"}else Th="missing";Ph()};var ji=function(a){"cfg"in Jd(void 0)||m.Id("cfg");Nh(a)};
var di=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));m.vb(vi);vi=m.ub(function(){var c=a[0],d=a[1],e=a[2];b.className="";var f=b.style;f.transitionDuration=f.webkitTransitionDuration=c+"ms";f.width=d+"%";m.fb(wi);wi=m.y(function(){b.className=e},c)},0)};
var ti=function(){var a=pi[0]+50;m.fb(wi);wi=m.y(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};var xi=function(){m.xb.call(this,"www/base");this.l=0};var yi=function(a){(a=a.detail.name)&&Bb(a)};m.ba=[];m.zi=m.zi||{};m.ea=this;qa="closure_uid_"+(1E9*Math.random()>>>0);ra=0;m.G=Date.now||function(){return+new Date};
Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return m.q.apply(null,c)}return(0,m.q)(this,a)};ua[" "]=m.fa;m.t(m.wa,Error);m.wa.prototype.name="CustomError";var Aa,Ba,Ca,Da,Ea,Fa,za;m.Ka=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};Aa=/&/g;Ba=/</g;Ca=/>/g;Da=/"/g;Ea=/'/g;Fa=/\x00/g;za=/[\x00&<>"']/;m.Ai=2147483648*Math.random()|0;m.Va=Array.prototype;m.Sa=m.Va.indexOf?function(a,b,c){return m.Va.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(m.ka(a))return m.ka(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
m.Bi=m.Va.lastIndexOf?function(a,b,c){return m.Va.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(m.ka(a))return m.ka(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};m.A=m.Va.forEach?function(a,b,c){m.Va.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
m.ie=m.Va.filter?function(a,b,c){return m.Va.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=m.ka(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var p=h[k];b.call(c,p,k,a)&&(e[f++]=p)}return e};m.Ci=m.Va.map?function(a,b,c){return m.Va.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=m.ka(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
m.Di=m.Va.reduce?function(a,b,c,d){d&&(b=(0,m.q)(b,d));return m.Va.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,m.A)(a,function(c,h){e=b.call(d,e,c,h,a)});return e};m.Ei=m.Va.some?function(a,b,c){return m.Va.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
m.Fi=m.Va.every?function(a,b,c){return m.Va.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};m.u.prototype.qb=!1;m.u.prototype.Oa=function(){return this.qb};m.u.prototype.dispose=function(){this.qb||(this.qb=!0,this.L())};m.u.prototype.L=function(){if(this.ab)for(;this.ab.length;)this.ab.shift()()};m.t(m.$a,m.u);m.g=m.$a.prototype;m.g.Hn=1;m.g.Zi=0;m.g.subscribe=function(a,b,c){var d=this.Bc[a];d||(d=this.Bc[a]=[]);var e=this.Hn;this.Ya[e]=a;this.Ya[e+1]=b;this.Ya[e+2]=c;this.Hn=e+3;d.push(e);return e};m.g.pf=function(a,b,c){if(a=this.Bc[a]){var d=this.Ya;if(a=m.Pa(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.Cc(a)}return!1};
m.g.Cc=function(a){if(0!=this.Zi)return this.j||(this.j=[]),this.j.push(a),!1;var b=this.Ya[a];if(b){var c=this.Bc[b];c&&m.Ta(c,a);delete this.Ya[a];delete this.Ya[a+1];delete this.Ya[a+2]}return!!b};m.g.W=function(a,b){var c=this.Bc[a];if(c){this.Zi++;for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];e=0;for(f=c.length;e<f;e++){var h=c[e];this.Ya[h+1].apply(this.Ya[h+2],d)}this.Zi--;if(this.j&&0==this.Zi)for(;c=this.j.pop();)this.Cc(c);return 0!=e}return!1};
m.g.clear=function(a){if(a){var b=this.Bc[a];b&&((0,m.A)(b,this.Cc,this),delete this.Bc[a])}else this.Ya.length=0,this.Bc={}};m.g.Xa=m.aa(3);m.g.L=function(){m.$a.D.L.call(this);delete this.Ya;delete this.Bc;delete this.j};m.cb=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};m.l("yt.config_",m.cb,void 0);m.l("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);m.jb=window.yt&&window.yt.msgs_||{};m.l("yt.msgs_",m.jb,void 0);m.Ff="Microsoft Internet Explorer"==window.navigator.appName;var Gi=m.n("yt.pubsub.instance_")||new m.$a;m.$a.prototype.subscribe=m.$a.prototype.subscribe;m.$a.prototype.unsubscribeByKey=m.$a.prototype.Cc;m.$a.prototype.publish=m.$a.prototype.W;m.$a.prototype.clear=m.$a.prototype.clear;m.l("yt.pubsub.instance_",Gi,void 0);var nb=m.n("yt.pubsub.subscribedKeys_")||{};m.l("yt.pubsub.subscribedKeys_",nb,void 0);var pb=m.n("yt.pubsub.topicToKeys_")||{};m.l("yt.pubsub.topicToKeys_",pb,void 0);var ob=m.n("yt.pubsub.isSynchronous_")||{};
m.l("yt.pubsub.isSynchronous_",ob,void 0);m.mb=m.n("yt.pubsub.skipSubId_")||null;m.l("yt.pubsub.skipSubId_",m.mb,void 0);m.g=m.xb.prototype;m.g.hA=function(){2==this.j||this.init()};m.g.enable=function(){this.j=1;(0,m.A)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.hA,this),this.subscribe("dispose-"+a,this.dispose,this),m.w("PAGE_NAME")==a&&m.yb(this))},this)};m.g.init=function(){m.vb(this.k);this.j=2;this.A&&this.A()};m.g.dispose=function(){this.j=3;m.vb(this.k);this.n&&this.n()};m.g.disable=function(){this.j=4;this.clear();try{this.dispose()}catch(a){m.hb(a)}};
m.g.subscribe=function(a,b,c){a=m.z(a,b,c);this.Ya.push(a);return a};m.g.clear=function(){m.qb(this.Ya);this.Ya=[]};var Ab=m.n("yt.modules.registry_")||{};m.l("yt.modules.registry_",Ab,void 0);var Kb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");var mc=m.Lb("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));m.Hi=RegExp("^[^\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");m.Ii=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");m.Mb.prototype.Ye=!0;m.Mb.prototype.Oe=function(){return this.j};m.Mb.prototype.toString=function(){return"Const{"+this.j+"}"};var Nb={};m.Pb.prototype.Ye=!0;var Qb={};m.Pb.prototype.Oe=function(){return this.j};var kc=Sb(""),jc=/^[-,."'%_!# a-zA-Z0-9]+$/;m.Tb.prototype.Ye=!0;m.Tb.prototype.Oe=function(){return this.j};m.Tb.prototype.vk=!0;m.Tb.prototype.Lg=function(){return 1};var Xb=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,Zb=/[()']|%5B|%5D|%25/g,$b={"'":"%27","(":"%28",")":"%29","%5B":"[","%5D":"]","%25":"%"},Ub={};ac.prototype.Ye=!0;ac.prototype.Oe=function(){return""};ac.prototype.vk=!0;ac.prototype.Lg=function(){return 1};var bc={};var ic,lc,Ji,dc;m.cc.prototype.vk=!0;m.cc.prototype.Lg=function(){return this.k};m.cc.prototype.Ye=!0;m.cc.prototype.Oe=function(){return this.j};ic=/^[a-zA-Z0-9-]+$/;lc=m.Lb("action","cite","data","formaction","href","manifest","poster","src");Ji=m.Lb("EMBED","IFRAME","LINK","OBJECT","SCRIPT","STYLE","TEMPLATE");dc={};m.Ki=m.gc("",0);var qc={};var tc=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,uc=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;m.g=m.wc.prototype;m.g.clone=function(){return new m.wc(this.x,this.y)};m.g.ceil=m.aa(5);m.g.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};m.g.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};m.g.scale=function(a,b){var c=m.la(b)?b:a;this.x*=a;this.y*=c;return this};t:{var Li=m.ea.navigator;if(Li){var Mi=Li.userAgent;if(Mi){m.yc=Mi;break t}}m.yc=""};var Oi,Kc,Jc,Si,Ti;m.Mf=zc();m.D=Ac();m.Fc=m.xc("Gecko")&&!(m.Ga(m.yc.toLowerCase(),"webkit")&&!Cc())&&!(m.xc("Trident")||m.xc("MSIE"))&&!Cc();m.Gc=m.Ga(m.yc.toLowerCase(),"webkit")&&!Cc();m.Gc&&m.xc("Mobile");m.Kf=m.xc("Macintosh");m.Jf=m.xc("Windows");m.Ni=m.xc("Linux")||m.xc("CrOS");Oi=m.ea.navigator||null;Oi&&m.Ga(Oi.appVersion||"","X11");m.Pi=m.xc("Android");m.Qi=m.Dc();m.Ri=m.xc("iPad");
Kc=function(){if(m.Mf&&m.ea.opera){var a=m.ea.opera.version;return m.na(a)?a():a}var a="",b=Ec();b&&(a=b?b[1]:"");return m.D&&!Cc()&&(b=Hc(),b>(0,window.parseFloat)(a))?String(b):a}();Jc={};Si=m.ea.document;Ti=Hc();m.Mc=!Si||!m.D||!Ti&&Cc()?void 0:Ti||("CSS1Compat"==Si.compatMode?(0,window.parseInt)(Kc,10):5);var Wc;Wc=!m.D||m.Lc(9);m.Ui=!m.Fc&&!m.D||m.D&&m.Lc(9)||m.Fc&&m.Ic("1.9.1");m.Vi=m.D&&!m.Ic("9");m.Wi=m.D||m.Mf||m.Gc;m.Xi=m.D&&!m.Lc(9);var Qc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};m.Yi=m.gd(!1);m.Zi=m.gd(!0);m.kd="StopIteration"in m.ea?m.ea.StopIteration:Error("StopIteration");m.id.prototype.next=function(){throw m.kd;};m.id.prototype.Ib=function(){return this};var rd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,pd=m.Gc;var Cd={},Bd=0,$i=m.n("yt.net.ping.workerUrl_")||null;m.l("yt.net.ping.workerUrl_",$i,void 0);m.Dd.prototype.Gb=function(){return{version:this.version,args:this.args}};m.Ed.prototype.toString=function(){return this.j};var aj=m.n("yt.pubsub2.instance_")||new m.$a;m.$a.prototype.subscribe=m.$a.prototype.subscribe;m.$a.prototype.unsubscribeByKey=m.$a.prototype.Cc;m.$a.prototype.publish=m.$a.prototype.W;m.$a.prototype.clear=m.$a.prototype.clear;m.l("yt.pubsub2.instance_",aj,void 0);m.bj=m.n("yt.pubsub2.subscribedKeys_")||{};m.l("yt.pubsub2.subscribedKeys_",m.bj,void 0);m.cj=m.n("yt.pubsub2.topicToKeys_")||{};m.l("yt.pubsub2.topicToKeys_",m.cj,void 0);m.dj=m.n("yt.pubsub2.isAsync_")||{};
m.l("yt.pubsub2.isAsync_",m.dj,void 0);m.l("yt.pubsub2.skipSubKey_",null,void 0);m.t(Hd,m.Dd);var $d=new m.Ed("timing-sent",Hd);var Vd=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},Qd=(0,m.q)(Vd.clearResourceTimings||Vd.webkitClearResourceTimings||Vd.mozClearResourceTimings||Vd.msClearResourceTimings||Vd.oClearResourceTimings||m.fa,Vd),Kd=Vd.mark?function(a){Vd.mark(a)}:m.fa;m.fe=m.qd;var le={enablejsapi:1},me={},ne={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};ke.prototype.clone=function(){var a=new ke,b;for(b in this){var c=this[b];"object"==m.ha(c)?a[b]=m.Ib(c):a[b]=c}return a};m.qe=null;m.ej=m.Gc?"webkit":m.Fc?"moz":m.D?"ms":m.Mf?"o":"";m.fj=m.n("yt.dom.getNextId_");if(!m.fj){m.fj=function(){return++gj};m.l("yt.dom.getNextId_",m.fj,void 0);var gj=0};m.g=m.te.prototype;m.g.Wa=null;m.g.type="";m.g.target=null;m.g.relatedTarget=null;m.g.currentTarget=null;m.g.data=null;m.g.source=null;m.g.state=null;m.g.keyCode=0;m.g.charCode=0;m.g.altKey=!1;m.g.ctrlKey=!1;m.g.shiftKey=!1;m.g.clientX=0;m.g.clientY=0;m.g.wheelDeltaX=0;m.g.wheelDeltaY=0;m.g.rotation=0;m.g.scale=1;m.g.changedTouches=null;m.g.preventDefault=function(){this.Wa.returnValue=!1;this.Wa.preventDefault&&this.Wa.preventDefault()};m.g.stopPropagation=m.aa(8);m.g.stopImmediatePropagation=m.aa(9);
var ue={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1};m.we=m.n("yt.events.listeners_")||{};m.l("yt.events.listeners_",m.we,void 0);var xe=m.n("yt.events.counter_")||{count:0};m.l("yt.events.counter_",xe,void 0);m.Be=/\s*;\s*/;m.g=m.ze.prototype;m.g.isEnabled=m.aa(10);m.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');m.da(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,m.G)()+1E3*c)).toUTCString();this.j.cookie=a+"="+b+e+d+c+f};
m.g.get=function(a,b){for(var c=a+"=",d=(this.j.cookie||"").split(m.Be),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};m.g.remove=function(a,b,c){var d=m.da(this.get(a));this.set(a,"",0,b,c);return d};m.g.yb=m.aa(11);m.g.Za=m.aa(12);m.g.isEmpty=m.aa(13);m.g.Xa=m.aa(2);m.g.Bf=m.aa(14);m.g.clear=function(){for(var a=m.Ae(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};m.De=new m.ze(window.document);m.De.k=3950;Ne.prototype.get=function(){var a;0<this.k?(this.k--,a=this.j,this.j=a.next,a.next=null):a=this.l();return a};Ne.prototype.put=function(a){this.n(a);this.k<this.A&&(this.k++,a.next=this.j,this.j=a)};var $e;var af=new Ne(function(){return new Re},function(a){a.reset()},100);Qe.prototype.add=function(a,b){var c=af.get();c.set(a,b);this.k?this.k.next=c:this.j=c;this.k=c};Qe.prototype.remove=function(){var a=null;this.j&&(a=this.j,this.j=this.j.next,this.j||(this.k=null),a.next=null);return a};Re.prototype.set=function(a,b){this.Od=a;this.scope=b;this.next=null};Re.prototype.reset=function(){this.next=this.scope=this.Od=null};var Te,Ve=!1,We=new Qe;gf.prototype.reset=function(){this.context=this.k=this.l=this.j=null;this.n=!1};var jf=new Ne(function(){return new gf},function(a){a.reset()},100);m.df.prototype.then=function(a,b,c){return m.qf(this,m.na(a)?a:null,m.na(b)?b:null,c)};m.bf(m.df);m.df.prototype.cancel=function(a){0==this.j&&Se(function(){var b=new rf(a);mf(this,b)},this)};m.df.prototype.J=function(a){this.j=0;ff(this,2,a)};m.df.prototype.F=function(a){this.j=0;ff(this,3,a)};
m.df.prototype.P=function(){for(var a=null;a=nf(this);)of(this,a,this.j,this.C);this.B=!1};var uf=Oe;m.t(rf,m.wa);rf.prototype.name="cancel";var yf={};Af.prototype.l=function(a){zf(this.j,"startFeedback",arguments)};Af.prototype.n=function(a){zf(this.j,"startHelp",arguments)};Af.prototype.k=function(a){zf(this.j,"loadChatSupport",arguments)};var hj=!1,ij="";
if(window.navigator.plugins&&window.navigator.plugins.length){var jj=window.navigator.plugins["Shockwave Flash"];jj&&(hj=!0,jj.description&&(ij=Cf(jj.description)));window.navigator.plugins["Shockwave Flash 2.0"]&&(hj=!0,ij="2.0.0.11")}else if(window.navigator.mimeTypes&&window.navigator.mimeTypes.length){var kj=window.navigator.mimeTypes["application/x-shockwave-flash"];(hj=kj&&kj.enabledPlugin)&&(ij=Cf(kj.enabledPlugin.description))}else try{var lj=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),hj=
!0,ij=Cf(lj.GetVariable("$version"))}catch(aaa){try{lj=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),hj=!0,ij="6.0.21"}catch(baa){try{lj=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash"),hj=!0,ij=Cf(lj.GetVariable("$version"))}catch(caa){}}}m.mj=hj;m.nj=ij;var qj;m.rh=m.xc("Firefox");m.oj=m.Dc()||m.xc("iPod");m.pj=m.xc("iPad");qj=m.xc("Android")&&!(Bc()||m.xc("Firefox")||zc()||m.xc("Silk"));m.qh=Bc();m.rj=m.xc("Safari")&&!(Bc()||m.xc("Coast")||zc()||Ac()||m.xc("Silk")||m.xc("Android"))&&!(m.Dc()||m.xc("iPad")||m.xc("iPod"));m.sj=function(){if(m.rh)return Df(/Firefox\/([0-9.]+)/);if(m.D||m.Mf)return Kc;if(m.qh)return Df(/Chrome\/([0-9.]+)/);if(m.rj&&!(m.Dc()||m.xc("iPad")||m.xc("iPod")))return Df(/Version\/([0-9.]+)/);if(m.oj||m.pj){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(m.yc))return a[1]+"."+a[2]}else if(qj)return(a=Df(/Android\s+([0-9.]+)/))?a:Df(/Version\/([0-9.]+)/);return""}();m.ga(Ef);Ef.prototype.getVersion=function(){return[this.j,this.k,this.l]};m.g=m.Of.prototype;m.g.clone=function(){return new m.Of(this.top,this.right,this.bottom,this.left)};m.g.contains=function(a){return m.Pf(this,a)};m.g.ceil=m.aa(4);m.g.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};m.g.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
m.g.scale=function(a,b){var c=m.la(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};var Rf={};m.tj=m.hd(function(){if(m.D)return m.Ic("10.0");var a=window.document.createElement("div"),b=m.Nf(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");b={style:c};if(!ic.test("div"))throw Error("Invalid tag name <div>.");if("DIV"in Ji)throw Error("Tag name <div> is not allowed for SafeHtml.");b=m.hc("div",b);m.nc(a,b);a=a.firstChild;b=a.style[m.Na("transition")];return""!=("undefined"!==typeof b?b:a.style[m.Qf(a,"transition")]||"")});var ag;m.Xf={};ag=!1;var vg,vj;m.uj=!m.D||m.Lc(9);vg=!m.D||m.Lc(9);vj=m.D&&!m.Ic("9");!m.Gc||m.Ic("528");m.Fc&&m.Ic("1.9b")||m.D&&m.Ic("8")||m.Mf&&m.Ic("9.5")||m.Gc&&m.Ic("528");m.Fc&&!m.Ic("8")||m.D&&m.Ic("9");m.cg.prototype.stopPropagation=m.aa(7);m.cg.prototype.preventDefault=function(){this.defaultPrevented=!0;this.Op=!1};m.wj=m.D?"focusin":"DOMFocusIn";m.xj=m.Gc?"webkitTransitionEnd":m.Mf?"otransitionend":"transitionend";m.t(m.dg,m.cg);
m.dg.prototype.init=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;d?m.Fc&&(m.va(d,"nodeName")||(d=null)):"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=m.Gc||void 0!==a.offsetX?a.offsetX:a.layerX;this.offsetY=m.Gc||void 0!==a.offsetY?a.offsetY:a.layerY;this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=
a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.Wa=a;a.defaultPrevented&&this.preventDefault()};m.dg.prototype.stopPropagation=m.aa(6);
m.dg.prototype.preventDefault=function(){m.dg.D.preventDefault.call(this);var a=this.Wa;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,vj)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};m.dg.prototype.ck=m.aa(15);var hg;m.fg="closure_listenable_"+(1E6*Math.random()|0);hg=0;m.jg.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.j[f];a||(a=this.j[f]=[],this.k++);var h=m.lg(a,b,d,e);-1<h?(b=a[h],c||(b.Jh=!1)):(b=new gg(b,this.src,f,!!d,e),b.Jh=c,a.push(b));return b};m.jg.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.j))return!1;var e=this.j[a];b=m.lg(e,b,c,d);return-1<b?(m.ig(e[b]),m.Ua(e,b),0==e.length&&(delete this.j[a],this.k--),!0):!1};m.jg.prototype.removeAll=m.aa(16);var qg="closure_lm_"+(1E6*Math.random()|0),xg={},tg=0,Ag="__closure_events_fn_"+(1E9*Math.random()>>>0);m.ga(m.Bg);m.Cg=m.n("yt.prefs.UserPrefs.prefs_")||{};m.l("yt.prefs.UserPrefs.prefs_",m.Cg,void 0);m.g=m.Bg.prototype;m.g.get=function(a,b){Eg(a);Dg(a);var c=void 0!==m.Cg[a]?m.Cg[a].toString():null;return null!=c?c:b?b:""};m.g.set=function(a,b){Eg(a);Dg(a);if(null==b)throw"ExpectedNotNull";m.Cg[a]=b.toString()};m.g.remove=function(a){Eg(a);Dg(a);delete m.Cg[a]};m.g.save=m.aa(17);m.g.clear=function(){m.Cg={}};var Og=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var Qg;var yj=m.yc,yj=yj.toLowerCase();if(m.Ga(yj,"android")){var zj=yj.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(zj)Qg=Number(zj[1]);else{var Aj={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},Bj=yj.match("("+m.Db(Aj).join("|")+")");Qg=Bj?Aj[Bj[0]]:0}}else Qg=void 0;m.t(m.Sg,Rg);m.Sg.prototype.Xa=m.aa(1);m.Sg.prototype.clear=function(){var a=m.md(this.Ib(!0)),b=this;(0,m.A)(a,function(a){b.remove(a)})};m.t(m.Tg,m.Sg);m.g=m.Tg.prototype;m.g.isAvailable=function(){if(!this.j)return!1;try{return this.j.setItem("__sak","1"),this.j.removeItem("__sak"),!0}catch(a){return!1}};m.g.set=function(a,b){try{this.j.setItem(a,b)}catch(c){if(0==this.j.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};m.g.get=function(a){a=this.j.getItem(a);if(!m.ka(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};m.g.remove=function(a){this.j.removeItem(a)};
m.g.Xa=m.aa(0);m.g.Ib=function(a){var b=0,c=this.j,d=new m.id;d.next=function(){if(b>=c.length)throw m.kd;var d;d=c.key(b++);if(a)return d;d=c.getItem(d);if(!m.ka(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};m.g.clear=function(){this.j.clear()};m.g.key=function(a){return this.j.key(a)};m.t(m.Ug,m.Tg);m.t(Vg,m.Tg);m.Yg.prototype.Gb=function(a){var b=[];Zg(this,a,b);return b.join("")};var bh={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},ah=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;m.ch.prototype.set=function(a,b){m.da(b)?this.j.set(a,m.Xg(b)):this.j.remove(a)};m.ch.prototype.get=function(a){var b;try{b=this.j.get(a)}catch(c){return}if(null!==b)try{return m.Wg(b)}catch(d){throw"Storage: Invalid value was encountered";}};m.ch.prototype.remove=function(a){this.j.remove(a)};m.t(dh,m.ch);dh.prototype.set=function(a,b){dh.D.set.call(this,a,fh(b))};dh.prototype.k=function(a){a=dh.D.get.call(this,a);if(!m.da(a)||a instanceof Object)return a;throw"Storage: Invalid value was encountered";};dh.prototype.get=function(a){if(a=this.k(a)){if(a=a.data,!m.da(a))throw"Storage: Invalid value was encountered";}else a=void 0;return a};m.t(m.gh,dh);m.gh.prototype.set=function(a,b,c){if(b=fh(b)){if(c){if(c<(0,m.G)()){m.gh.prototype.remove.call(this,a);return}b.expiration=c}b.creation=(0,m.G)()}m.gh.D.set.call(this,a,b)};m.gh.prototype.k=function(a,b){var c=m.gh.D.k.call(this,a);if(c)if(!b&&m.hh(c))m.gh.prototype.remove.call(this,a);else return c};m.t(m.ih,m.gh);var Cj,Dj;Cj=new m.Ug;m.kh=Cj.isAvailable()?new m.ih(Cj):null;Dj=new Vg;m.lh=Dj.isAvailable()?new m.ih(Dj):null;m.t(oh,m.u);m.g=oh.prototype;m.g.getId=function(){return this.R};m.g.Ul=function(a,b){this.Oa()||(sh(this,a),yh(this,b),this.P&&uh(this))};m.g.Rs=function(){return this.Hb};
m.g.cB=function(){if(!this.Ga){var a=zh(this);if(a&&"html5"==Ch(this))this.J="html5",this.P||this.dg();else if(Dh(this),this.J="html5",a&&this.wb)this.B.appendChild(this.wb),this.dg();else{this.j.loaded=!0;var b=(0,m.q)(function(){var a=this.B,b=this.j.clone();m.n("yt.player.Application.create")(a,b);this.dg()},this);this.C=b;this.Ga=!0;a?this.C():(this.j.assets.js2?(this.C=a=(0,m.q)(function(){m.rc(this.j.assets.js2,b);this.C=b},this),m.rc(this.j.assets.js,a)):m.rc(this.j.assets.js,this.C),m.Ng(this.j.assets.css))}}};
m.g.bB=function(){var a=this.j.clone();if(!this.F){var b=xh(this);b&&(this.F=window.document.createElement("span"),this.F.tabIndex=0,this.nb.push(m.K(this.F,"focus",(0,m.q)(this.Wo,this))),this.S=window.document.createElement("span"),this.S.tabIndex=0,this.nb.push(m.K(this.S,"focus",(0,m.q)(this.Wo,this))),m.$c(this.F,b),m.ad(this.S,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==Ch(this)?(this.J="flash",this.P||Lg(a,!1,(0,m.q)(this.dg,this))):(Dh(this),this.J=
"flash",this.j.loaded=!0,m.Ig(this.B,a),this.dg())};m.g.Wo=function(){xh(this).focus()};
m.g.dg=function(){var a=xh(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(c){}if(b)if(this.Ga=!1,a.isNotServable&&a.isNotServable(this.j.args.video_id))wh(this);else{ph(this);this.P=!0;a=xh(this);a.addEventListener&&(this.O=Ah(this,a,"addEventListener"));a.removeEventListener&&(this.bb=Ah(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),d=0;d<b.length;d++){var e=b[d];this.k[e]||(this.k[e]=Ah(this,a,e))}for(var f in this.A)this.O(f,
this.A[f]);uh(this);this.gb&&this.gb(this.k);this.sa.W("onReady",this.k);a.apiProxyReady&&a.apiProxyReady()}else this.pc=m.y((0,m.q)(this.dg,this),50)};m.g.pB=function(){return this.P};m.g.yd=function(a,b){if(!this.Oa()){var c=th(this,b);if(c){if(!m.Ra(this.Bd,a)&&!this.A[a]){var d=Bh(this,a);this.O&&this.O(a,d)}this.sa.subscribe(a,c);"onReady"==a&&this.P&&m.y(m.r(c,this.k),0)}}};m.g.aA=function(a,b){if(!this.Oa()){var c=th(this,b);c&&this.sa.pf(a,c)}};
m.g.os=function(a){a=a?cd:bd;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.F||b==this.S||(b.focus(),b!=window.document.activeElement));)b=a(b)};m.g.IA=function(a){m.B("a11y-announce",a)};m.g.wy=function(a){var b={};b.volume=(0,window.isNaN)(a.volume)?nh().volume:m.vc(a.volume,0,100);b.muted=void 0==a.muted?nh().muted:a.muted;m.jh("yt-player-volume",b,2592E3)};m.g.uy=function(a){5==a&&wh(this)};m.g.xy=function(a){m.B("WATCH_LATER_VIDEO_ADDED",a)};
m.g.yy=function(a){m.B("WATCH_LATER_VIDEO_REMOVED",a)};m.g.jy=function(a){if(!m.dd(this.B,m.ye(a)))this.k.onExternalMouseMove()};m.g.iy=function(){m.mg(window.document,"mousemove",this.jy,!1,this)};m.g.ky=function(){this.Pc&&(this.Bb||(this.Ra=m.Rc(window.document)),this.U||(this.U=m.mg(window,"scroll",this.Ez,!1,this)));this.Bb=!0};m.g.ly=function(){this.U&&(m.wg(this.U),this.U=null);this.Bb=!1};m.g.bp=function(a){this.Bb&&!this.Pc&&a.preventDefault()};
m.g.Ez=function(){this.Ra&&window.scrollTo(this.Ra.x,this.Ra.y)};
m.g.dB=function(){Dh(this);this.J="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');b=
this.j.messages.player_fallback||a;a=m.E("player-unavailable");m.E("unavailable-submessage")&&a&&(m.E("unavailable-submessage").innerHTML=b,(b=m.F("icon",a))&&m.pc(b,"icon")&&(b.src=m.C(b,"icon")),m.J(a,"hid"),m.I(m.E("player"),"off-screen-trigger"))};m.g.Ts=function(){return this.J||Ch(this)};m.g.Ss=function(){return this.Nb};m.g.cancel=function(){if(this.C){var a=this.C,b=m.sc(this.j.assets.js);window.spf.script.ignore(b,a)}m.fb(this.pc);this.Ga=!1};
m.g.L=function(){Dh(this);this.ib=null;for(var a in this.A)m.ea[this.A[a]]=null;this.k=null;delete this.B;delete this.n;this.j&&(this.Hb=this.j=this.j.fallback=null);oh.D.L.call(this)};var Gh={},Fh="player_uid_"+(1E9*Math.random()>>>0);var Ej=m.n("yt.abuse.botguardInitialized")||pe;m.l("yt.abuse.botguardInitialized",Ej,void 0);var Fj=m.n("yt.abuse.invokeBotguard")||m.re;m.l("yt.abuse.invokeBotguard",Fj,void 0);var Gj=m.n("yt.player.exports.navigate")||m.Me;m.l("yt.player.exports.navigate",Gj,void 0);var Hj=m.n("yt.player.embed")||m.Eh;m.l("yt.player.embed",Hj,void 0);var Ij=m.n("yt.player.destroy")||m.Jh;m.l("yt.player.destroy",Ij,void 0);var Jj=m.n("yt.player.cancelAll")||Ih;m.l("yt.player.cancelAll",Jj,void 0);
var Kj=m.n("yt.player.getPlayerByElement")||m.Kh;m.l("yt.player.getPlayerByElement",Kj,void 0);var Lj=m.n("yt.player.exports.feedbackStart")||m.Zf;m.l("yt.player.exports.feedbackStart",Lj,void 0);var Mj=m.n("yt.player.exports.feedbackShowArticle")||m.bg;m.l("yt.player.exports.feedbackShowArticle",Mj,void 0);var Nj=m.n("yt.util.activity.init")||m.Fe;m.l("yt.util.activity.init",Nj,void 0);var Oj=m.n("yt.util.activity.getTimeSinceActive")||m.He;m.l("yt.util.activity.getTimeSinceActive",Oj,void 0);
var Pj=m.n("yt.util.activity.setTimestamp")||Ge;m.l("yt.util.activity.setTimestamp",Pj,void 0);var Oh,Th;m.Sh=null;Th="";var Wh=[];var bi,wi,vi,ci,ei,mi,gi,ii,pi;ci=0;ei=[900,60,"waiting"];mi=[500,99,"waiting"];gi=[300,60,"waiting"];ii=[400,99,"waiting"];pi=[300,101,"done"];window.yt=window.yt||{};m.l("yt.setConfig",m.ab,void 0);m.l("yt.getConfig",m.w,void 0);m.l("yt.hasMsg",m.ib,void 0);m.l("yt.pubsub.publish",m.B,void 0);m.l("yt.pubsub.subscribe",m.z,void 0);m.l("yt.setMsg",function(a){bb(m.jb,arguments)},void 0);m.l("yt.setGoogMsg",function(a){bb(m.jb,arguments)},void 0);m.l("yt.timing.report",ae,void 0);
m.l("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+a[e]);c.rt=d.join(",");for(var f in b)"_"!=f.charAt(0)&&(c[f]=b[f]);a=m.w("TIMING_INFO")||{};"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);Yd(c)},void 0);m.l("ytcsi.tick",m.Id,void 0);m.t(xi,m.xb);
xi.prototype.enable=function(){window.onload=Yh;window.onunload=Zh;window.onerror=$h;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfrequest",ai),window.addEventListener("spfpartprocess",fi),window.addEventListener("spfpartdone",ki),window.addEventListener("spfprocess",li),window.addEventListener("spfdone",ni),window.addEventListener("spferror",qi),window.addEventListener("spfreload",ri),window.addEventListener("spfjsbeforeunload",yi)),a.config=a.config||{},
window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",si),this.subscribe("dispose",ui)):window.spf.dispose();this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
xi.prototype.init=function(){xi.D.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&m.w("PAGEFRAME_JS")?(b=m.w("PAGEFRAME_JS"),c=function(){window.ytPageFrameLoaded=!0;m.n("ytbin.www.pageframe.setup")()}):a&&(a=m.n("yt.www.masthead.loadSearchbox"))&&a();var a=m.w("JS_COMMON_MODULE"),d=m.w("JS_PAGE_MODULES");d||(d=[a]);a=m.w("JS_DELAY_LOAD",void 0);0<a?(m.fb(this.l),this.l=m.y(function(){b&&m.rc(b,c);window.spf.script.require(d)},a)):(b&&m.rc(b,
c),window.spf.script.require(d));Mh();var a=!!m.n("yt.reactLoaded"),e=m.w("REACT_JS");!a&&e&&m.rc(e,function(){m.l("yt.reactLoaded",!0,void 0)})};xi.prototype.dispose=function(){m.fb(this.l);var a=m.n("ytbin.www.pageframe.cancelSetup");a&&a();m.gb(Oh);if(a=m.Qh())a.removeEventListener("onReady",Ph),a.removeEventListener("onStateChange",Ph);xi.D.dispose.call(this)};
xi.prototype.disable=function(){xi.D.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfrequest",ai),window.removeEventListener("spfpartprocess",fi),window.removeEventListener("spfpartdone",ki),window.removeEventListener("spfprocess",li),window.removeEventListener("spfdone",ni),window.removeEventListener("spferror",qi),window.removeEventListener("spfreload",ri),window.removeEventListener("spfjsbeforeunload",yi));window.onload=null;window.onunload=null;window.onerror=null};
m.zb(new xi);})(_yt_www);
